# Gaussian PDF and CDF

#### Gaussian PDF function = (1 / sqrt(2 * PI * poison**2)) * exp**-(((x-meu)**2) / (2 * poison**2) )

Scipy is the fastest to calculate these type of complex equations. We ALWAYS have to use scipy.

In [4]:
from scipy.stats import norm
import numpy as np

In [2]:
# We find the PDF of zero first, as an example
norm.pdf(0)

0.3989422804014327

In [3]:
# Since we are working with Gaussian pdf, mean can be other than 0 & stand.Deviation(variance**2) can be other than 1
norm.pdf(0, loc=5, scale=10)
#loc argument gives mean...scale gives standard_Deviation...means variance of 100

0.035206532676429952

Thus we see that this has a much smaller probability density...since mean and variances are changed

#### We can calculate the pdf of many random points at the same time...using rand() to generate random points and then using scipy

In [5]:
r = np.random.randn(10)    # Generating PDF of 10 random numbers
norm.pdf(r)

array([ 0.26415992,  0.2022081 ,  0.37892134,  0.36424636,  0.36544156,
        0.38901008,  0.29919188,  0.39623371,  0.36268198,  0.18635966])

#### The actuall Gaussian pdf have exponential, so we can take pog on both sides...log saves time much more
#### Also, rather than multiplication, summation saves up much time...SO we use log PDF rather than normal Gaussian pdf

In [6]:
# This log pdf is just given simply using another function of scipy
norm.logpdf(r)

array([-1.33120062, -1.59845789, -0.97042663, -1.00992482, -1.00664889,
       -0.94415002, -1.20667017, -0.92575107, -1.01422891, -1.6800768 ])

#### We now need CDF(cumulative densty func). This is the integral of PDF from -infinity to x.
#### This integral is not possible to find mathematically as an expression...but we can do this by computing manually.

In [7]:
norm.cdf(r)

array([ 0.18193036,  0.87814793,  0.37414345,  0.33484175,  0.66233075,
        0.58883556,  0.77595196,  0.4535384 ,  0.33121685,  0.10863765])

In [8]:
# Similar to pdf, there is also log of cdf
norm.logcdf(r)

array([-1.70413131, -0.12994022, -0.98311601, -1.09409726, -0.41199023,
       -0.52960832, -0.25366467, -0.79067535, -1.10498197, -2.2197372 ])