# Matrix products and More operation

In [1]:
import numpy as np

In [6]:
#Define a matrix
A = np.array([[1,2],[3,4]])

In [3]:
#Inverse of matrix A:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [4]:
#checking if this inverse is correct or not (multiplying with each other gives Identity matrices) :
A.dot(Ainv) , Ainv.dot(A)

(array([[  1.00000000e+00,   1.11022302e-16],
        [  0.00000000e+00,   1.00000000e+00]]),
 array([[  1.00000000e+00,   4.44089210e-16],
        [  0.00000000e+00,   1.00000000e+00]]))

In [7]:
#determinant of A:
np.linalg.det(A)

-2.0000000000000004

In [8]:
#diagonal of matrix A:
np.diag(A)

array([1, 4])

This shows the diagonal elements jsut as a 1d array. In matrix form where all other elements are considered as zeroes, we use this function as pass the diagonal elements in a different way:

In [9]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [10]:
np.diag([1])

array([[1]])

In [11]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### Outer and inner product
#### Inner product is also known as Dot product

In [12]:
a = np.array([1,2])
b = np.array([3,4])

#Outer product:
np.outer(a, b)

array([[3, 4],
       [6, 8]])

In [14]:
#Inner product(dot product):
np.inner(a,b) , a.dot(b)

(11, 11)

In [16]:
#Matrix Trace, i.e. sum of the diagonal elements of the matrix:
np.diag(A).sum(), np.trace(A)

(5, 5)

### Eigen Values and Eigen vectors (https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors)

#### We need symmetric matric for eigen values and vectors calculations
#### creating a random Gaussian dataframe...each sample=rows....each feature=columns

In [17]:
#dataset with 100 samples and 3 unique features
X = np.random.randn(100,3)
#Gives the covariance of the dataset:
cov = np.cov(X)
#To see if the covariance is right
cov.shape

(100, 100)

In [19]:
# BUT we require a symmetric matrix for eigen things.....so lets get covariance of the transpose of X
cov = np.cov(X.T)
cov

array([[ 1.07261751,  0.00845853, -0.03807501],
       [ 0.00845853,  1.18208145,  0.05235943],
       [-0.03807501,  0.05235943,  1.08050683]])

#### eig() or eigh() can be used from np object
#### But for symmetric (transpose and original is equal) & Hermitian (conjugate transpose and original are equal) eigh() can also be used.
#### Since cov is symmetric, we use eigh()

In [20]:
np.linalg.eigvals(cov)

array([ 1.02635061,  1.10420948,  1.2046457 ])

In [21]:
np.linalg.eigh(cov)

(array([ 1.02635061,  1.10420948,  1.2046457 ]),
 array([[-0.64035316,  0.76591129, -0.05768653],
        [ 0.27580023,  0.29938268,  0.91340257],
        [-0.71685568, -0.56899026,  0.40294915]]))

Here, first tuple shows the eigne values and the 2nd tuple shows the eigen vectors arranged as columns

In [22]:
np.linalg.eig(cov)

(array([ 1.02635061,  1.10420948,  1.2046457 ]),
 array([[-0.64035316,  0.76591129, -0.05768653],
        [ 0.27580023,  0.29938268,  0.91340257],
        [-0.71685568, -0.56899026,  0.40294915]]))

Eig() and eigh() here produces same results. Important fact to notice is  that, the arrangement of the eigen values and vectors can be different on eig() and eigh()......